### ISSUE TITLE
percent_over_qscore_cumulative returns NaN

### ISSUE THREAD

**Issue by amacbride** [Illumina/interop#121] opened 2017-04-05 23:37 UTC
Hello,

When trying to use percent_over_qscore_cumulative() and total_over_qscore_cumulative(), I'm getting NaN, whereas the local histogram versions of these calls work fine.

is_cumulative_empty() is returning false, so I know it's not trying to calculate over an empty set.

Is there anything else that needs to be done for percent_over_qscore_cumulative() that isn't required for percent_over_qscore() ?

Thanks,
Andrew

#define INTEROP_VERSION "v1.0.19"

Example using percent_over_qscore and total_over_qscore:
>HLFG2BGXY       30      569525.000000   95.297417
>HLGC7BGXY       30      618893.000000   95.195122

Same runs, substituting percent_over_qscore_cumulative and total_over_qscore_cumulative:
>HLFG2BGXY       30      0.000000        nan
>HLGC7BGXY       30      0.000000        nan

**Comment by ezralanglois** [comment] 2017-04-05 23:38
If you load the q-metrics from run metrics, then it should be created.

I am guessing that you are not, if you are doing this at a lower level, then you need to call `populate_cumulative_distribution` on the q-metric set.

**Comment by amacbride** [comment] 2017-04-06 04:48
That appears to have solved that problem, thanks! The scores I'm getting appear to be identical to those I got from the non-cumulative versions: is that to be expected?

(The scores I'm getting are reasonable, but slightly higher than those gotten by other members of my team who are using SAV, so I'm trying to look into possible discrepancies.)

**Comment by ezralanglois** [comment] 2017-04-06 14:58
- Which version of SAV are you comparing against? I ask because this code will be used in later versions of SAV, 2.1.x and later. 
- What are you comparing or what is your objective? Is this the Q-score histogram plot?
- Also, what language are you using? Just curious.

I would suggest starting with a higher level application like `plot_qscore_histogram` . This library provides all the plotting logic used by SAV. SAV only calls these functions and then uses a C# plotting library to render the plot.

We work from a `run_metrics` object in SAV, which you can use to load all the InterOps or a single InterOp file. This class will take care of certain logic after loading an InterOp file (such as `populate_cumulative_distribution`) that you would have to call yourself if you were using a lower level class such as q_metric_set.

**Comment by amacbride** [comment] 2017-04-06 20:28
- They're currently using SAV 1.9.1.
- I'm porting code I originally wrote last year against Interop v1.0.6-2-g49643cd to the most recent version. All I actually want is the Q30 count and percent values, since this is part of a QC check for an automated production pipeline.
- I'm using C++ wrapped in JNA to provide a Java interface to the rest of the system.

I'm mostly just trying to make sure that the by-hand checks that people are making with SAV correspond to the automated checks that are done by the production pipeline.

I'll give the run_metrics interface a try. What's the most straightforward way to get a q_metric or q_metric_set from it, once it's loaded?

**Comment by ezralanglois** [comment] 2017-04-06 21:14
Couple more questions
1. Do you want read or run level information like on the SAV summary tab? I am asking because you might be able to do less work, by calling the summary logic.
2. Or do you really need tile level information? How are you checking the histograms against SAV tile by tile? It is not clear to me.

I was just looking over our examples and they are pretty dated. I created a gist here:
https://gist.github.com/ezralanglois/8500c8e3e17c9d1ac249b91be5821dde

The code in the applications is also a pretty good place to see how to use run metrics and the other logic functions:
https://github.com/Illumina/interop/tree/master/src/apps

**Comment by amacbride** [comment] 2017-04-06 21:20
My test code with run_metrics gave me the same answer as before (no change between the local and cumulative histograms.) Is that what I should expect the behavior to be?

Here's my basic test method:

```c++
void load_metrics (char *rundir) {
    int qvalue = 30;
    std::vector<unsigned char> valid_to_load;
    logic::utils::list_summary_metrics_to_load(valid_to_load);
    run_metrics run;

    run.clear();
    run.read (rundir, valid_to_load, 1);

    metric_set<q_metric> &qMetricSet = run.get<q_metric>();

    unsigned int qvalueIndex = qMetricSet.index_for_q_value(qvalue);

    q_metric& mset_cumulative = qMetricSet.at(0);
    q_metric& mset_local = qMetricSet.at(0);

    printf ("debug: run_metrics cumulative histogram is %lu, %f\n",
            mset_cumulative.total_over_qscore_cumulative(qvalueIndex),
            mset_cumulative.percent_over_qscore_cumulative(qvalueIndex));

    printf ("debug: run_metrics local histogram is %u, %f\n",
            mset_local.total_over_qscore(qvalueIndex),
            mset_local.percent_over_qscore(qvalueIndex));
}

```

**Comment by ezralanglois** [comment] 2017-04-06 21:25
So, you are only looking at the first entry for your test. A single tile at a single cycle.
So the cumulative will be the same if the first metric in the metric set is cycle 1 (no guarantee there, but it should be).

The cumulative distribution is just the sum over all preceding cycles for a single tile.

**Comment by amacbride** [comment] 2017-04-06 22:51
Ah -- that explains it (and makes sense.)

Looking at the docs, I can see how I would get the bins from the header (`get_bins`), but I haven't figured out how to get the header from the metric_set -- is there an accessor method I haven't found yet? (I'm looking at http://illumina.github.io/interop/classillumina_1_1interop_1_1model_1_1metric__base_1_1metric__set.html)

**Comment by ezralanglois** [comment] 2017-04-06 22:52
The header is a base class of the metric set, so qMetricSet .get_bins() will work.

**Comment by amacbride** [comment] 2017-04-07 00:23
(Thank you for being patient.)

I'm having a chicken-and-egg confusion here.

I've loaded the `run_metrics`, and have gotten the qMetricSet (of type `metric_set<q_metric>`) via `run.get<q_metric>();`

I've gotten the bins ( `std::vector<illumina::interop::model::metrics::q_score_bin>`) via qMetricSet.`get_bins()`.

All well and good.

My question is, what's the proper way to get a single `q_metric` object upon which I can call percent_over_qscore_cumulative (30, bins) ? It seems weird to call it on a single member of the set when it's an operation over many sets, but there doesn't appear to be an equivalent on the set itself (I would have expected something like qMetricSet.`percent_over_qscore_cumulative(30)`, with bins being implicit.)

What am I missing? Essentially, I'm asking how to calculate the cumulative histogram over the set of all the bins, as you pointed out above. I haven't seen anything relevant in the example code.

**Comment by ezralanglois** [comment] 2017-04-07 00:50
What are you trying to calculate? Are you trying to reproduce the plot in SAV?

There may be a single function to do this, but it will not be apart of the metric set.

**Comment by nudpa** [comment] 2017-04-07 14:55
Hello Andrew,

Just to add to Robert's last point, if want to calculate metrics such as %Q30 over the entire run (as opposed to over each tile individually), that's more in the domain of our summary logic than the individual metric logic (https://github.com/Illumina/interop/blob/master/src/apps/summary.cpp, for more info). We calculate both yield (which is defined as the total number of bases in the Q-histogram) and %Q30 on run, read, and read/lane levels here.

**Comment by ezralanglois** [comment] 2017-04-11 01:34
I will close this out. Please feel free to reopen if you have more questions on this topic or open another issue.

**Comment by amacbride** [comment] 2017-04-27 19:01
Hi there, sorry it took a bit to get back to this. I'm trying to reproduce the number for the "SAV Non-Indexed Total" programmatically via the library, so that it's congruent with what the lab folks are getting via SAV. (I had them upgrade to 2.1.8)

**Comment by ezralanglois** [comment] 2017-04-27 19:31
I suggest looking at the code in: https://github.com/Illumina/interop/blob/master/src/apps/summary.cpp

This is pretty much the same code that SAV uses, and you won't have to do much work to get it.

**Closed** 2017-05-22 19:35 UTC
Labels: question
