### ISSUE TITLE
interop does not install: Python 2.7.7, gcc 4.4.7 / 4.7.2

### ISSUE THREAD

**Issue by jbsysadmin** [Illumina/interop#120] opened 2017-04-05 19:40 UTC
This occurs on Centos 6.8. Any leads on how to add this to Python 2.7.x?

Pip install attempt: 
pip install -f https://github.com/Illumina/interop/releases/latest interop

Result:
   _Downloading/unpacking interop
     Could not find a version that satisfies the requirement interop (from versions: linux_gcc46_release, msvc14_win64_Release, osx_clang_release, osx_py36_clang_release)
   Cleaning up...
   No distributions matching the version for interop_

Pip install attempt with wheel:
   pip install --use-wheel --no-index interop-1.0.18-cp27-cp27mu-linux_x86_64.whl

Result:
   _Ignoring indexes: https://pypi.python.org/simple/
interop-1.0.18-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform._

Another post suggested building a .whl file with cmake. However that did not work.

Cmake attempt: 
   cmake --build . --target package_wheel
Result:
   _gmake: *** No rule to make target `package_wheel'.  Stop._

**Comment by ezralanglois** [comment] 2017-04-05 20:45
Several things can be wrong with the binary distribution:

1. Python is configured differently. Our Linux Wheels for Python2.7 are built against UCS-4 (cp27mu), but your Python may be built against UCS-2. 
You can check this as follows:
`python -c "import sys;print sys.maxunicode"`
1114111 means ucs-4
65535 means ucs-2

2. There may be some difference in the libc version on both system. We are building on Ubuntu with GCC 4.6, I think it should still work with CentOS should have the same libc version.

**Comment by jbsysadmin** [comment] 2017-04-05 20:57
Thank you. I'll stay away from the binary, as 1) the check here showed "65535" 2) gcc 4.6 wasn't in any attempt so far.

**Comment by ezralanglois** [comment] 2017-04-05 21:44
Copying this from the previous thread https://github.com/Illumina/interop/issues/117: 

> -- InterOp v1.0.16
> CMake Warning at src/ext/CMakeLists.txt:11 (message):
> Swig version 1 found, but version 3.x or later is required. Skipping
> interface generation.
> -- Could NOT find CSharp (missing: CSHARP_TYPE CSHARP_VERSION CSHARP_COMPILER)
> -- GTest include directory not found
> -- Enable Shared CRT for GTest
> -- Could NOT find GTest (missing: GTEST_LIBRARY)
> -- GMock include directory not found
> -- Could NOT find GMock (missing: GMOCK_LIBRARY)

So, the package_wheel target can be missing for the following reasons (sorry for the repeat, but I want to keep everything contained on this thread):
1. CMake cannot find the Python Interpreter 
2. CMake cannot find the Python Libraries
3. CMake cannot find Numpy
4. CMake cannot find Swig or Swig is too old (This is the one I forgot from the previous thread)

It looks like you need to upgrade your Swig to version 3.

**Comment by ezralanglois** [comment] 2017-04-06 00:16
It looks like we may be able to add a UCS-2 build information from the following:
https://github.com/travis-ci/travis-ci/issues/5107

**Comment by jbsysadmin** [comment] 2017-04-06 16:37
We have a  later swig 3.x; swig-<version>/bin and swig-<version>/share/swig/<version> are in PATH.
cmake still doesn't see it. Any lead?

**Comment by ezralanglois** [comment] 2017-04-06 17:01
That is strange.
A couple things to check:

1.  `swig -version`, without adding the path, it gives you something like 3.x.x
2. Delete your old CMakeCache.txt and run configure again.

If that does not work, then you can always workaround it as follows:
`cmake <path/to/source> -DSWIG_EXECUTABLE=/path/to/swig3`

On my system I would do something like:
From the source directory:
`mkdir build`
`cd build`
`cmake ../ -DSWIG_EXECUTABLE=/usr/local/bin/swig`

**Comment by jbsysadmin** [comment] 2017-04-06 18:57
Hello. I've some progress. I rebuilt swig and pcre.  Various items needed to be added to LB_LIBRARY_PATH to keep things going. cmake ../ finally ran; I needed -DPYTHON_LIBRARIES, -DPYTHON_INCLUDE_DIRS, and -DPYTHON_EXECUTABLE. 

However, cmake --build . --target package_wheel fails at 79%.

Errors below:

[ 79%] Linking CXX shared module interop/_py_interop_summary.so
/usr/bin/ld: python2.7.7/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
python2.7.7/lib/libpython2.7.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
gmake[3]: *** [src/ext/python/interop/_py_interop_summary.so] Error 1
gmake[2]: *** [src/ext/python/CMakeFiles/_py_interop_summary.dir/all] Error 2
gmake[1]: *** [src/ext/python/CMakeFiles/package_wheel.dir/rule] Error 2
gmake: *** [package_wheel] Error 2

**Comment by ezralanglois** [comment] 2017-04-06 19:14
It looks like you set the Python library to be libpython2.7.a instead of `libpython2.7.so`.
You need to point to `libpython2.7.so`

**Comment by jbsysadmin** [comment] 2017-04-06 21:43
Thank you. I inherited the Python 2.7.7, and assumed it was build with shared.  A valuable lesson, I think. I'll try another build.

**Comment by ezralanglois** [comment] 2017-04-06 21:57
If you are building Python yourself, I would recommend, as an alternative, using [Miniconda](https://conda.io/miniconda.html) or [Anaconda](https://www.continuum.io/downloads) instead.

We do all our builds with Miniconda. Just be sure to install numpy if you are using Miniconda
`conda install numpy`

**Comment by jbsysadmin** [comment] 2017-04-06 23:50
Almost made it to the end with I revised Python build (after adding Numpy.)
Any thoughts on the item below?

*****
Scanning dependencies of target package_wheel
[100%] Creating Python wheel package
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
gmake[3]: *** [src/ext/python/CMakeFiles/package_wheel] Error 1
gmake[2]: *** [src/ext/python/CMakeFiles/package_wheel.dir/all] Error 2
gmake[1]: *** [src/ext/python/CMakeFiles/package_wheel.dir/rule] Error 2

**Comment by jbsysadmin** [comment] 2017-04-06 23:56
Disregard my last; I forgot to pip install wheel. I'll try to add interop now...

**Comment by jbsysadmin** [comment] 2017-04-07 00:01
I don't see the new .whl file, from "cmake --build . --target package_wheel"
Where do I look?

**Comment by ezralanglois** [comment] 2017-04-07 00:14
Inside the build directory, it should be in ./src/ext/python/

Alternatively, you could run `find . -name "*.whl"`

**Comment by jbsysadmin** [comment] 2017-04-07 00:25
I ran find before asking; it missed it. I may have had typo. 
Thanks, this build finally succeeded.

**Comment by ezralanglois** [comment] 2017-04-07 00:50
Great.

**Comment by jbsysadmin** [comment] 2017-04-10 20:17
Hello again. There is a report that when one  runs either "run_metrics.read" (with run_folder or other args) there is a seg fault. Any leads?
(see: https://github.com/Illumina/interop/blob/masterdocs/src/PythonIntroTutorial.ipynb)

**Comment by ezralanglois** [comment] 2017-04-10 20:44
There is a known bug with python 3. I will have a pull request out shortly to fix it and we should have a new build in a couple days.

Otherwise, I would need information like your OS version, GCC version, Python Version things like that to narrow it down.

So far, we have tested on several versions of Ubuntu and Centos 5, 6 and 7, but only with Python2.7 until recently.

**Comment by jbsysadmin** [comment] 2017-04-10 21:14
This just failed, same result, Python 3.6.1. Both that and 2.7.7 under Centos 6.8. gcc 4.4.7

**Comment by ezralanglois** [comment] 2017-04-10 21:40
Interesting. Are you using the prebuilt wheels on GitHub, building the InterOp library for each version of Python from scratch?

**Comment by jbsysadmin** [comment] 2017-04-11 14:58
I built the .whl with “cmake-3.5.2/usr/local/bin/cmake --build . --target package_wheel.” I rebuilt interopt against python 3.6.1

**Comment by ezralanglois** [comment] 2017-04-11 15:12
The new Python wheel for Python 3.6 is up for version 1.0.20.
This was built using the Anaconda version of GCC, which uses an older version of libc.

Could you give that a try?
`pip install -f https://github.com/Illumina/interop/releases/latest interop`

Also, to help debug this issue, what do you see when you run:
`python -m interop --version`
and 
`python -m interop --test`

**Comment by ezralanglois** [comment] 2017-04-11 15:29
Ok, I was just able to reproduce a problem, this may be the same problem you are having.

If you run the following, then you may see a segfault:

`python -c "from interop import py_interop_run_metrics;run = py_interop_run_metrics.run_metrics();run.read('file/not/found')"`

or you may see the following message:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda2\lib\site-packages\interop\py_interop_run_metrics.py", line 375, in read
    return _py_interop_run_metrics.run_metrics_read(self, *args)
RuntimeError: <Swig Object of type 'illumina::interop::xml::xml_file_not_found_exception *' at 0x00000000022F8630>
swig/python detected a memory leak of type 'illumina::interop::xml::xml_file_not_found_exception *', no destructor found.`

But, if you add `py_interop_run` to the import, then everything works fine:
`python -c "from interop import py_interop_run_metrics,py_interop_run;run = py_interop_run_metrics.run_metrics();run.read('file/not/found')"`

You should get:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda2\lib\site-packages\interop\py_interop_run_metrics.py", line 375, in read
    return _py_interop_run_metrics.run_metrics_read(self, *args)
interop.py_interop_run.xml_file_not_found_exception: cannot open file file/not/found\RunInfo.xml
C:\projects\interop\src\interop\model\run\info.cpp::illumina::interop::model::run::info::read_file (237)`

**Comment by jbsysadmin** [comment] 2017-04-11 15:42
That wheel didn't allow me to get as far as I did yesterday. On "from interop import py_interop_run_metrics, py_interop_run, py_interop_summary" I got: ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found. Yesterday, I ran the above and more, only to seg fault on "run_metrics.read"

**Comment by ezralanglois** [comment] 2017-04-11 15:57
Thanks for the report. I believe I know how to fix this issue.

**Comment by jbsysadmin** [comment] 2017-04-11 15:58
Just spotted your item above, will try...

**Comment by jbsysadmin** [comment] 2017-04-11 16:21
I got the same thing again. All attempts have run run interactively (within Python)
I used this sequence: 
from interop import py_interop_run_metrics, py_interop_run, py_interop_summary;
run_metrics = py_interop_run_metrics.run_metrics();
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0);
py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load);
run_folder = run_metrics.read(run_folder, valid_to_load);
The exception happens on the last step, "Segmentation fault (core dumped)"

**Comment by jbsysadmin** [comment] 2017-04-11 16:28
Just spotted: /python -m interop --version yields:
Traceback (most recent call last):
  File "/nfs/goldstein/software/python3.6.1-x86_64_shared/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/goldstein/software/python3.6.1-x86_64_shared/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/goldstein/software/python3.6.1-x86_64_shared/lib/python3.6/site-packages/interop/__main__.py", line 5, in <module>
    from CoreTests import CoreTests
ModuleNotFoundError: No module named 'CoreTests'

**Comment by jbsysadmin** [comment] 2017-04-11 16:29
python -m interop --test, same thing.

**Comment by ezralanglois** [comment] 2017-04-11 19:17
I should be able to fix everything you described, except for the segfault.

The next release of InterOp will have GlibC statically linked, so you should not get that error. Ideally, this will also fix the segfault.

If you could run cmake in a clean directory, and post the log here, then I can check if there is some library problem that is causing the segfault. I suspect this is a build issue, which I am unable to reproduce here. That may determine the problem faster.

I fixed the import CoreTests problem for python3. For some reason, I cannot reproduce the problem in Python2.

**Comment by ezralanglois** [comment] 2017-04-14 15:55
I created a number of Python wheels in the latest release, which are now built using centos 5. I tested them on centos 6.8 using miniconda, and they worked fine.

If you are still having issues, I would recommend using [miniconda](https://conda.io/miniconda.html) for your python installation: 

```
pip install -f https://github.com/Illumina/interop/releases/latest interop
```

**Comment by jbsysadmin** [comment] 2017-04-14 19:09
Say, this last one hasn't had any seg faults at the prior steps. The folks here can resume their tests. Thanks for your help so far.

**Comment by ezralanglois** [comment] 2017-04-15 01:53
Great. I will close this out. Please open a new one if you encounter another problem.

**Closed by ezralanglois** 2017-04-15 01:53 UTC
Labels: question
